### ISSUE TITLE
Phaser not appearing in lib folder after Build

### ISSUE THREAD

**Issue by Cloov** [funzeye/Phaser-Project-Template-Javascript#1]
Hi,

I've followed all the instructions for setting up the template, and I'm building successfully, but the lib folder never receives the Phaser files, and so when I run index.html I get a 404 on phaser.js. Any ideas on what might be happening?

Thanks

**Comment by funzeye** [comment]
I will check it out. no one else has had this issue so it may be something you are doing incorrectly...I will double check anyway and get back to you asap.

**Comment by Cloov** [comment]
Thanks, I got it sorted though!
